#!/usr/bin/env python3
"""
Build script: bundles gemini-web2api-worker TypeScript sources into a single JS module
for direct deployment via Cloudflare Workers API.

Strips type annotations and concatenates modules.
"""
import re
import sys
import os

# Source files in dependency order (imported before importer)
SOURCE_FILES = [
    "src/utils/log.ts",
    "src/utils/response.ts",
    "src/utils/sse.ts",
    "src/version.ts",
    "src/models.ts",
    "src/config.ts",
    "src/gemini.ts",
    "src/tools.ts",
    "src/multimodal.ts",
    "src/router.ts",
    "src/handlers/chat.ts",
    "src/handlers/responses.ts",
    "src/handlers/google.ts",
    "src/index.ts",
]

def strip_types(code: str) -> str:
    """Remove TypeScript type annotations, imports, and interfaces."""
    # Remove import type { ... } statements
    code = re.sub(r'^import\s+type\s*\{[^}]*\}\s*from\s*["\'][^"\']*["\']\s*;?\n?', '', code, flags=re.MULTILINE)
    # Remove regular imports (they become inlined in bundle)
    code = re.sub(r'^import\s+\{[^}]*\}\s*from\s*["\'][^"\']*["\']\s*;?\n?', '', code, flags=re.MULTILINE)
    # Remove import default
    code = re.sub(r'^import\s+\w+\s*from\s*["\'][^"\']*["\']\s*;?\n?', '', code, flags=re.MULTILINE)
    # Remove export default (keep the object)
    code = re.sub(r'^export\s+default\s+', '', code, flags=re.MULTILINE)
    # Remove export function/const/class
    code = re.sub(r'^export\s+(function|const|class|let|var|async\s+function)\s+', r'\1 ', code, flags=re.MULTILINE)
    # Remove export { ... }
    code = re.sub(r'^export\s*\{[^}]*\}\s*;?\n?', '', code, flags=re.MULTILINE)
    # Remove interface declarations
    code = re.sub(r'^interface\s+\w+[^\{]*\{[^}]*\}\s*\n?', '', code, flags=re.MULTILINE)
    # Remove type declarations
    code = re.sub(r'^type\s+\w+\s*=.*\n?', '', code, flags=re.MULTILINE)
    # Remove : Type annotations after params
    code = re.sub(r'(:\s*(string|number|boolean|void|Promise<[^>]*>|Promise<void>|any|unknown|null|undefined|never|\w+\[\]|\[\w+,\s*\w+\]|Record<string,[^>]+>|IterableIterator<[^>]*>|Generator<[^>]*>|AsyncGenerator<[^>]*>|ReadableStream|WritableStreamDefaultWriter<[^>]*>|WritableStreamDefaultWriter|TransformStream<[^>]*>|Response))\b', '', code)
    # Remove generic type params <T> etc
    # Be careful not to remove comparison operators
    code = re.sub(r'<([A-Z]\w*(?:\s*extends\s+\w+(?:<[^>]*>)?)?)>', '', code)
    # Remove as Type assertions
    code = re.sub(r'\s+as\s+\w+(?:\[\])?(?:<[^>]*>)?', '', code)
    # Remove const assertions
    code = re.sub(r'\s+as\s+const', '', code)
    # Remove | undefined and | null from union types in annotations
    code = re.sub(r'(:\s*\w+)\s*\|\s*(undefined|null)\s*', r'\1', code)
    # Clean up empty lines
    code = re.sub(r'\n\s*\n\s*\n', '\n\n', code)
    return code

def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    src_dir = os.path.join(base_dir)
    
    # Output header
    lines = [
        "// gemini-web2api — Cloudflare Worker bundle",
        "// Auto-generated by build.py",
        "// Original source: gemini-web2api-worker/",
        "",
        "import { parseGoogleFunctionCalls } from './tools';",
        "",
    ]
    
    for filename in SOURCE_FILES:
        filepath = os.path.join(src_dir, filename)
        with open(filepath) as f:
            code = f.read()
        code = strip_types(code)
        # Wrap in module scope
        lines.append(f"// === {filename} ===")
        lines.append(code)
        lines.append("")
    
    output = "\n".join(lines)
    outpath = os.path.join(src_dir, "dist", "worker.js")
    os.makedirs(os.path.dirname(outpath), exist_ok=True)
    with open(outpath, 'w') as f:
        f.write(output)
    print(f"Bundled {len(SOURCE_FILES)} files -> {outpath}")
    print(f"Size: {len(output)} bytes")

if __name__ == '__main__':
    main()
